### ISSUE TITLE
Not installing mongodb

### ISSUE THREAD

**Issue by caprocha** [gozoinks/unifi-pfsense#173]
Install script starting output this error:

pkg: https://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/mongodb34-.txz: Not Found

*********************************

Not sure if it´s a repository error or mongodb34 was intentionally removed (file does not exist anymore). Can´t we go with mongodb 3.6 or 4.0 (more recent) ? 

Actually on repo are these packages: 

https://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/mongodb36-3.6.17.txz
https://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/mongodb40-4.0.12_1.txz

**Comment by dvdp** [comment]
I had the same issue - mongdb34 and dependency packages are no longer available from https://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/ - I solved things by a manual install:
/usr/sbin/pkg add -f  https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/icu-62.1_2,1.txz
/usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/boost-libs-1.68.0_1.txz
/usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/mongodb34-3.4.16.txz

(didn't check other than FreeBSD:11:amd64 - most likely the same story)

After that, the contoller started up nicely (note that I make a backup tar of my /usr/local/UniFi dir, I remove whatever has been installed in /usr/local/UniFi and untar my backup , works like a charm)

I hope the UniFi developers soon switch to mongodb40 ...

**Comment by dvdp** [comment]
Just checked - if you modify the script and use release_3 instead of latest, mongodb34 should install nicely - no manual installs needed
Lines to change:
# FreeBSD package source:
FREEBSD_PACKAGE_URL="https://pkg.freebsd.org/${ABI}/latest/All/"
change to 
FREEBSD_PACKAGE_URL="https://pkg.freebsd.org/${ABI}/**release_3**/All/"

# FreeBSD package list:
FREEBSD_PACKAGE_LIST_URL="https://pkg.freebsd.org/${ABI}/latest/packagesite.txz"
change to
FREEBSD_PACKAGE_LIST_URL="https://pkg.freebsd.org/${ABI}/**release_3**/packagesite.txz"

**Comment by dvdp** [comment]
** are introduced by selecting bold face - sorry for that

**Comment by caprocha** [comment]
running fine here with mongodb40, script could install this version.

**Comment by blueknight768** [comment]
Could we add mongodb40 to the script?

**Comment by dlasher** [comment]
Script still doesn't work out of the box with 2.4.5 - had to manually install the (3) packages above.
