### ISSUE TITLE
Mongodb use small files instead

### ISSUE THREAD

**Issue by kennylam777** [gozoinks/unifi-pfsense#21]
As my pfsense have only 4GB SSD and only 3.1GB root partition, there was a error that my disk space is not enough for mongodb

my workaround is to remove the symbolic link in /usr/local/UniFi/bin/mongodb, but using following shell script instead
# 
# !/bin/sh

/usr/local/bin/mongod --smallfiles "$@"

**Comment by gozoinks** [comment]
Interesting. Were you not able to achieve the same results with the configuration file?

This is more of an issue with mongodb than with unifi-pfsense, but since pfsense is commonly run on minimal hardware like yours, I am inclined to make a note about this in the readme. 

Since editing the configuration file is probably preferable to using a wrapper script, I would be interested to know whether that would work in your case.

**Comment by kennylam777** [comment]
Replacing link with shell script with extra argument (The method I mentioned) worked in my case.

I tired to edit configuration file (/usr/local/etc/mongodb.conf) and added a line "smallfiles = true" but no luck, I just don't know if the mongodb instance that launched by UniFi will load (/usr/local/etc/mongodb.conf).

**Comment by mattwire** [comment]
Add the following to unifi/data/system.properties:
unifi.db.extraargs=--smallfiles

**Comment by jmcphail** [comment]
I believe this issue has been addressed and can now be closed.

**Comment by gozoinks** [comment]
Thank you!
