### ISSUE TITLE
Packages Updated

### ISSUE THREAD

**Issue by Timotevin10** [gozoinks/unifi-pfsense#61]
Greetings,

New install on 2.3.3.a.20170203.1331

It appears these packages in the script may need to be updated:
pcre-8.39_1.txz  --> pcre-8.40.txz
openjdk8-8.112.16_3.txz --> openjdk8-jre-8.121.13.txz

**Comment by jmcphail** [comment]
I tried installing with openjdk8-jre vs openjdk8 and the UniFi controller seems to work, but snappyjava fails to install as it requires openjdk8.  I am not sure if we need snappyjava or not, I believe it was found to be needed to adopt newer AP hardware and firmwares.  Otherwise the Unifi software seems to install fine with jre.  Maybe this is better, as it might have less dependencies.

See #62

**Comment by gozoinks** [comment]
The new method of installing packages should avoid this issue.
