### ISSUE TITLE
mongod --smallfiles

### ISSUE THREAD

**Issue by theeddie** [gozoinks/unifi-pfsense#63]
I suggest adding --smallfiles to the monogod script startup command

**Comment by jmcphail** [comment]
Yes, this has been discussed before on issue #21 where it was suggested to:
Add the following to unifi/data/system.properties:
unifi.db.extraargs=--smallfiles

Does it makes sense to do this for all installations, or only ones with a partition less than a certain size?

**Comment by gozoinks** [comment]
Having now a second request, this is probably of some non-trivial value to implement. I would think it should be conditional upon the partition size. What should be the threshold? 4GB?

**Comment by theeddie** [comment]
I would say for all it limits he install to 1.5 gigs instead of 3gigs which is a lot for a router 

Get Outlook for iOS




On Fri, Feb 10, 2017 at 10:44 AM -0600, "James McPhail" <notifications@github.com> wrote:












Yes, this has been discussed before on issue #21 where it was suggested to:

Add the following to unifi/data/system.properties:

unifi.db.extraargs=--smallfiles


Does it makes sense to do this for all installations, or only ones with a partition less than a certain size?

**Comment by jmcphail** [comment]
I can't find any reason to not have --smallfiles on by default.  For larger UniFi databases it could negatively impact performance due to file fragmentation.  Without --smallfiles, the preallocation of db files (in particular the journaling) is significant.

Anything under 4GB would be a good start.
`df -k | awk '$NF=="/"{print $2}'`

**Comment by jmcphail** [comment]
Add in #64
