### ISSUE TITLE
Package Category

### ISSUE THREAD

**Issue by jmcphail** [gozoinks/unifi-pfsense#68]
Do you think the UniFi package should fall under `net`, `net-mgmt` or other category?
See:
* <https://doc.pfsense.org/index.php/Package_Port_Directory_Structure>
* <https://doc.pfsense.org/index.php/Package_Port_List>

```shell
root@bsd-builder:~/pfSense-ports # find . -maxdepth 2 -name "pfSense-pkg*" -print
./benchmarks/pfSense-pkg-iperf
./dns/pfSense-pkg-bind9
./emulators/pfSense-pkg-Open-VM-Tools
./ftp/pfSense-pkg-FTP_Client_Proxy
./ftp/pfSense-pkg-tftpd
./mail/pfSense-pkg-mailreport
./net-mgmt/pfSense-pkg-darkstat
./net-mgmt/pfSense-pkg-iftop
./net-mgmt/pfSense-pkg-net-snmp
./net-mgmt/pfSense-pkg-nrpe
./net-mgmt/pfSense-pkg-softflowd
./net-mgmt/pfSense-pkg-zabbix-agent
./net-mgmt/pfSense-pkg-zabbix-proxy
./net/pfSense-pkg-Avahi
./net/pfSense-pkg-LADVD
./net/pfSense-pkg-OpenBGPD
./net/pfSense-pkg-Quagga_OSPF
./net/pfSense-pkg-Status_Traffic_Totals
./net/pfSense-pkg-arping
./net/pfSense-pkg-cellular
./net/pfSense-pkg-freeradius2
./net/pfSense-pkg-haproxy-devel
./net/pfSense-pkg-haproxy
./net/pfSense-pkg-mtr-nox11
./net/pfSense-pkg-ntopng
./net/pfSense-pkg-pfBlockerNG
./net/pfSense-pkg-routed
./net/pfSense-pkg-siproxd
./www/pfSense-pkg-Lightsquid
./www/pfSense-pkg-squid
./www/pfSense-pkg-squidGuard
./security/pfSense-pkg-acme
./security/pfSense-pkg-nmap
./security/pfSense-pkg-openvpn-client-export
./security/pfSense-pkg-snort
./security/pfSense-pkg-sudo
./security/pfSense-pkg-suricata
./security/pfSense-pkg-tinc
./sysutils/pfSense-pkg-AutoConfigBackup
./sysutils/pfSense-pkg-Backup
./sysutils/pfSense-pkg-Cron
./sysutils/pfSense-pkg-LCDproc
./sysutils/pfSense-pkg-Notes
./sysutils/pfSense-pkg-RRD_Summary
./sysutils/pfSense-pkg-Service_Watchdog
./sysutils/pfSense-pkg-Shellcmd
./sysutils/pfSense-pkg-System_Patches
./sysutils/pfSense-pkg-apcupsd
./sysutils/pfSense-pkg-blinkled
./sysutils/pfSense-pkg-gwled
./sysutils/pfSense-pkg-nut
./sysutils/pfSense-pkg-syslog-ng
```

**Comment by gozoinks** [comment]
The value of a separate category for management tools is not clear to me, and the  assortment of packages in each category seems to support a guess that the value is unclear to most maintainers as well. 

However, If the distinction between net and net-mgmt is the implementation of a protocol rather than the administration of a service, then it seems like net-mgmt would be the more appropriate category for the UniFi controller, which is clearly a tool for the administration of UniFi equipment. It involves a variety of services and protocols, but network management could easily be considered the primary function of the UniFi controller. 

Since the more specific category exists and seems to fit the purpose of the tool, I would be inclined to use it. 

What do you think?

**Comment by jmcphail** [comment]
Agreed that `net-mgmt` seems like the most appropriate match.  Maybe @jim-p could shed some insight on the package category convention.

**Comment by jmcphail** [comment]
Just to add to the confusion:
<https://forum.pfsense.org/index.php?board=15.0>
