### ISSUE TITLE
README contains no info regarding install and logs paths

### ISSUE THREAD

**Issue by ssbarnea** [gozoinks/unifi-pfsense#91]
I think that the README file should mention where it does install unifi controller software and where we can find the logs. As someone new to the project I was surprised not to find any mention on this and I found nothing related to it in `/var/log`, so I ended up raising this enhancement request ;)

Update: I was able to spot installed UniFi inside `/usr/local/UniFi` but the logs directory from there contains only `mongodb.log` even if the web gui is clearly running.... so I am still looking for a way to find what is causing #90

**Comment by gnkidwell** [comment]
This is currently documented in the readme under uninstall process. Closing this.

**Comment by malakaisbest** [comment]
still I'm unable to find log files
I checked in `/usr/local/UniFi/logs` and `/var/log/unifi`.but there is no any server.log file.
any help ??

**Comment by malakaisbest** [comment]
> still I'm unable to find log files
> I checked in `/usr/local/UniFi/logs` and `/var/log/unifi`.but there is no any server.log file.
> any help ??

when i run manually through `/usr/local/bin/java -jar /usr/local/UniFi/lib/ace.jar start` it makes log files in `/root/logs/server.log` and `/root/logs/server.log`
but
when i run through `service unifi.sh start` it not make any log files

**Comment by jmbwell** [comment]
Ubiquiti has changed how logging works. Controller logs (network events etc) are available only through the web UI. Service logs (to see why the java service won't start, for example) are not saved to a file by default. To see that output, the procedure is to run it manually or interactively, as you describe, so that you can see the stdout output.

I suppose you could also modify unifi.sh to redirect stdout to a file of your choice.
